# Generated by Django 4.2.1 on 2023-05-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'Flex (misc) page', 'verbose_name_plural': 'Flex (misc) pages'},
        ),
    ]
