# Generated by Django 4.2.1 on 2023-05-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testtimonials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimodial',
            old_name='quoute',
            new_name='quote',
        ),
    ]
