# Generated by Django 4.2.1 on 2023-06-12 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Enter your facebook URL ')),
                ('twitter', models.URLField(blank=True, help_text='Enter your twiter URL ')),
                ('instagram', models.URLField(blank=True, help_text='Enter your instargram URL')),
                ('youtube', models.URLField(blank=True, help_text='Enter your youtube URL')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
